### ISSUE TITLE
Intersection with Million Songs Dataset

### ISSUE THREAD

**Issue by kyr0** [allthemusicllc/libatm#2]
Hi,

watching the TED talk brought me to the idea to enhance libatm with a simple function to compare all the melodies generated with MIDI melodies available in the http://millionsongdataset.com/ 

Filtering for copyrightable melodies in the set (some are too old already etc.) allthemusic could release a dataset of def. "free melodies" one could use today because it's "copyrighted" by allthemusic (green spot).

Also, the website could be enhanced with a web audio midi player (I could help with this) where you can choose from "free" melodies at random or selective by scale, mode etc.

Best,
Aron

**Comment by kyr0** [comment]
Million Song Dataset is 8 years old. So there is still a gap of popular music tracks and melodies of the last 8 years to be filled out.

**Comment by allthemusicllc** [comment]
@kyr0 we are planning a couple different projects that are adjacent to what you describe here. Once we get started we'll put the code on GitHub, and always appreciate PRs. Stay tuned!
