### ISSUE TITLE
I did exactly the same - years before

### ISSUE THREAD

**Issue by ewewo2** [allthemusicllc/libatm#3]
Hello Damien, Hello Rubin,

I've just read about your project (all possible melodies) a couple of hours ago. I did exactly the same and I started the project about 7 years ago. I can proof it because I uploaded large parts of my created melodies to external servers (e. g. box.net) which have time stemps of 2014. I even stepped a lot of steps furher: I tried to generate countless chord melodies (almost the half of all possible variations in a 4 chord scenario) and "full" MIDI Songs, too, which contain up to 80 bars. I have several terrabytes of generated MIDI Data. 

I decided to NOT release any of this past to public. You will face the same problem. You declared a huge amount of melodies as CC0 but you are not the original creator ALL of them (copyright is even not the related issue in the first place) . I am not sure if you know what you did... You re-created pre-existing melodies and you did not only gave them away for free, you told the world that they can be used for almost all purposes - but there ARE a lot of melodies included in this library who will have ownership by 3rd parties.

Besides song rights, there are a lot of MIDI and and audio loop based companies, who have a copyright of millions of that files you declared as CC0 and you have no option to filter that at all!

It is comparable to someone uploading a Michael Jackson Song and it declare it as Public Domain - it won't work out and it will result in lawsuits. Times thousand in this case.

The next main thing is: there ARE owner rights, even if the product is declared as "CC0". The user of "your" files is NOT allowed to claim to be the creator - this right is exclusively granted to the original creator of the CC0 content.

Sincerly,
Wolfgang

**Comment by ewewo2** [comment]
*It is comparable to someone uploading a Michael Jackson COVER Song

**Comment by allthemusicllc** [comment]
Thanks for your feedback Wolfgang! Glad to know others are (or have been) working on similar problems.
